# Generated by Django 5.2.5 on 2026-03-04 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-created_at'], 'verbose_name': 'Actividad Genérica', 'verbose_name_plural': 'Actividades Genéricas'},
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título de la Lección')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to=settings.AUTH_USER_MODEL, verbose_name='Creador')),
            ],
            options={
                'verbose_name': 'Lección',
                'verbose_name_plural': 'Lecciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Contenido (use {gap} para los huecos)')),
                ('interaction_type', models.CharField(choices=[('drag_and_drop', 'Arrastrar y Soltar'), ('text_input', 'Escribir texto')], default='text_input', max_length=20, verbose_name='Tipo de Interacción')),
                ('correct_answers', models.JSONField(verbose_name='Respuestas Correctas (JSON)')),
                ('options', models.JSONField(blank=True, null=True, verbose_name='Opciones (solo para Arrastrar)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='activities.lesson', verbose_name='Lección')),
            ],
            options={
                'verbose_name': 'Ejercicio',
                'verbose_name_plural': 'Ejercicios',
                'ordering': ['order', 'id'],
            },
        ),
    ]
