# Generated by Django 5.2.5 on 2026-03-04 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_alter_activity_options_lesson_exercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='activities.activity', verbose_name='Actividad'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='activities.lesson', verbose_name='Lección'),
        ),
    ]
