# Generated by Django 6.0.2 on 2026-03-04 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_achievement_alter_exercise_lesson_page_attempt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attempt',
            name='page',
        ),
        migrations.AddField(
            model_name='attempt',
            name='exercise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='activities.exercise'),
        ),
    ]
