# Generated by Django 5.2.5 on 2026-03-05 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0006_alter_page_unique_together_page_activity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='page',
            name='activity',
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
    ]
