# Generated by Django 5.2.5 on 2026-03-05 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0007_remove_exercise_activity_remove_page_activity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='activities.lesson'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='activities.exercise'),
        ),
    ]
